version: "3"
services:
  frontend:
    build:
      context: ./web-admin
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - frontend
